name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      image_tag: 
        description: " docker image tag"
        required: true
        default: "latest"  

jobs:
  trigger-build:
    uses: ./.github/workflows/workflow1.yaml
    with: 
      image_tag: ${{ github.event.inputs.image_tag}}