name: First Workflow

on:
  workflow_dispatch:
    inputs:
      image_tag: 
        required: true
        default: latest 
        type: string 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: building docker file
        run: docker build -t nginximage:${{github.event.inputs.image_tag}} .
